apiVersion: demo.github.com/v1alpha1
kind: Helloworld
metadata:
  labels:
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/instance: helloworld-sample
    app.kubernetes.io/part-of: helloworld-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: helloworld-operator
  name: helloworld-sample
spec:
  replicas: 2
  ingress:
    ingressClassName: nginx
    rules:
      - host: ingress.zte.com.cn  
        http:
          paths:
            - path: /helloworld
              pathType: Prefix
              backend:
                service:
                  name: service-helloworld-sample
                  port:
                    number: 80
